# Generated by Django 5.2.1 on 2025-05-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numcalc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculation',
        ),
    ]
